# seed for the random number generators, to make things reproducible
seed: 0


# telescope_type_key: telescope_type_name
telescope_events_key: telescope_events
array_events_key: array_events
runs_key: runs

multiple_telescopes: True


array_event_column: array_event_id

class_name: gamma_array

energy:
  regressor : |
    ensemble.RandomForestRegressor(
      n_estimators=150,
      max_features='sqrt',
      n_jobs=-1,
      max_depth=12,
    )
  target_column: mc_energy

  # define the number of cross validations to perform
  n_cross_validations : 3

  # Define the name of the category you want to find. The default is 'gamma_energy'.
  # It will be written as <class_name>_prediction into the file when applying the model.


  # Define the name of the column that contains the name of the telescope in case you're working
  # with mulitple telescopes and telescope types
  telescope_type_key: telescope_type_name
  output_name: gamma_array_energy_prediction

  log_target: True

  features:
    - gamma_energy_prediction_mean
    - gamma_energy_prediction_std
    - gamma_prediction_mean
    - gamma_prediction_std
    - num_triggered_sst
    - num_triggered_mst
    - num_triggered_lst
    - h_max
    - distance_to_reconstructed_core_position
    #- h_max_uncert (alles nan??)
    - total_intensity

