multiple_telescopes: True

selection:
    gamma_prediction_mean:
      - '>='  # needs to be in quotes because > and ! are special character in yaml
      - 0.05 ## predictions on diffuse gammas very low, just for debugging
