---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(levelname)s - %(asctime)s - %(name)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: ERROR
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: preprocessing_info.log
        encoding: utf8

    error_file_handler:
        class: logging.FileHandler
        level: ERROR
        formatter: simple
        filename: preprocessing_errors.log
        encoding: utf8

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
...


