chunksize: 20

allowed_cameras:
  - LSTCam
  - NectarCam
  - DigiCam

integrator: NeighborPeakWindowSum
cleaning_method: tailcuts_clean
cleaning_level:
  LSTCam:
    - 3.5
    - 7.5
    - 2
  NectarCam:
    - 3
    - 5.5
    - 2
  DigiCam:
    - 2
    - 4.5
    - 2

names_to_id:
  LSTCam: 1
  NectarCam: 2
  FlashCam: 3
  DigiCam: 4
  CHEC: 5

types_to_id:
  LST: 1
  MST: 2
  SST: 3

allowed_ids:
  - 4