aspell -t -c content/00_abstract.tex
aspell -t -c content/01_introduction.tex
aspell -t -c content/02_cta.tex
#aspell -t -c content/03_methods.tex
aspell -t -c content/04_analysis.tex
#aspell -t -c content/05_ghsep.tex
#aspell -t -c content/06_energy.tex
#aspell -t -c content/07_position.tex
#aspell -t -c content/08_conclusion.tex
